export const apiGetInforByGoogleLogin = "https://www.googleapis.com/oauth2/v3/userinfo"

export const apiGetListAuthor = "user/getListAuthor"
export const apiGetDetailProfile = "user/getDetailProfile"
export const apiGetDetailAuthour = "user/getDetailAuthour"
export const apiLogin = "user/login"
export const apiLoginByGoogle = "user/loginByGoogle"
export const apiRegister = "user/register"
export const apiRegisterByGoogle = "user/registerByGoogle"
export const apiUpdateProfile = "user/updateProfile"
export const apiChangePassword = "user/changePassword"
export const apiGetListUser = "user/getListUser"
export const apiDeactiveAccount = "user/deactiveAccount"
