export const apiGetInforByGoogleLogin = "https://www.googleapis.com/oauth2/v3/userinfo"

export const apiGetListAuthor = "user/getListAuthor"
export const apiGetDetailProfile = "user/getDetailProfile"
export const apiLogin = "user/login"
export const apiLoginByGoogle = "user/loginByGoogle"
export const apiRegister = "user/register"
export const apiRegisterByGoogle = "user/registerByGoogle"
export const apiUpdateProfile = "user/updateProfile"
export const apiChangePassword = "user/changePassword"
export const apiGetListUser = "user/getListUser"
export const apiDeactiveAccount = "user/deactiveAccount"
export const apiFollowOrUnfollowComic = "user/followOrUnfollowComic"
export const apiBuyPremium = "user/buyPremium"
export const apiHandleExpiredPremium = "user/handleExpiredPremium"
export const apiCheckEmail = "user/checkEmail"
export const apiForgotPassword = "user/forgotPassword"
export const apiGetDetailAuthor = "user/getDetailAuthor"